pom version bump

diff --git a/.github/workflows/finalization-workflow.yml b/.github/workflows/finalization-workflow.yml
--- a/.github/workflows/finalization-workflow.yml
+++ b/.github/workflows/finalization-workflow.yml
@@ -39,7 +39,10 @@ jobs:
           echo $lastTag
           IFS='.' read -r X Y Z <<< "$lastTag"
           X="${X//v/}"    # tag version to pom version
-          ((Z++)) || {echo "UNABLE TO DETERMINE THE POM VERSION" 1>&2 && exit 99;}
+          ((Z++)) || {
+            echo "UNABLE TO DETERMINE THE POM VERSION" 1>&2
+            exit 99
+          }
           mvn versions:set -DnewVersion="$X.$Y.$Z"
           echo "Version updated"
           mvn clean package > mvn-output.log
